
title: Prateek Boga | Amateur Astrophysicist
name: Prateek Boga
description: Amateur Astrophysicist exploring exoplanets and cosmic mysteries
theme: minima
paginate: 5
paginate_path: /blogs/page:num/
